[phases.setup]
nixPkgs = ["python312"]

[phases.install]
cmds = ["pip install --no-cache-dir uvicorn fastapi pandas numpy scikit-learn pydantic python-jose[cryptography] passlib[bcrypt] python-dotenv"]

[phases.start]
cmds = ["uvicorn main:app --host 0.0.0.0 --port $PORT"]